### ISSUE TITLE
Non functioning

### ISSUE THREAD

**Issue by EllriNidhogg** [DaedalusGame/Immersive-Cowardice#3]
just tried this mod on w/ 

Mods:

[✔️] immersive_cowardice-1.1

[✔️] ImmersiveEngineering-1.16.4-4.1.2-129

[✔️] Jade-1.16.3-2.2.1

[✔️] jei-1.16.4-7.6.0.58

[✔️] Patchouli-1.16.4-48

forge-1.16.4-35.1.28-launcher.jar

The mod didn't appear to do anything at all? Did I miss a setup step or something?

**Comment by DaedalusGame** [comment]
Seems to work fine for me, smokers and blast furnaces get heated just fine and i'm betting that arc furnace electrodes also insert fine?
