### ISSUE TITLE
Enabling this mod server-side throws error

### ISSUE THREAD

**Issue by Enterprise12nx01** [DaedalusGame/Immersive-Cowardice#6]
Tested when disabling this mod in 1.16.5 forge 36.2.35
I get an error saying "Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode"
https://zerobin.net/?60e46c547dbad9f2#F7e1CtLHBOmsfvF8rz7omHIKVTm090GM0kpG6O2NsLs=

**Comment by DaedalusGame** [comment]
*Emendatus Enigmatica is throwing datapack errors
